global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: my-application
  honor_labels: true
  static_configs:
  - targets: ['python-application:5000']

- job_name: prometheus
  honor_labels: true
  scrape_interval: 10s
  static_configs:
  - targets: ['localhost:9091']

- job_name: my-application2
  honor_labels: true
  static_configs:
  - targets: ['localhost:81']